'use client';
import React, { useEffect, useState } from 'react';
import { Typography, Empty, Switch, Form, Row, Col, Input, Modal, message } from 'antd';
import { useRouter } from 'next/navigation';
import AgentReferralHeader from '@/components/agentreferral/PartnerListingHeader';
import AgentReferralTable from '@/components/agentreferral/PartnerListingTable';
import AgentReferralGrid from '@/components/agentreferral/PartnerListingGrid';
import ConfirmationModal from '@/components/common/ConfirmationModal';
import PartnerDetailModal from '@/components/agentreferral/PartnerdetailModal';
import { useAppDispatch, useAppSelector } from '@hooks/redux';
import { IAgentReferralPartner } from '@redux/feature/agentReferral/IAgentReferralState';
import {
  createAgentReferral,
  deleteAgentReferral,
  fetchAllAgentReferral,
  updateAgentReferral,
} from '@redux/feature/agentReferral/agentReferralThunk';
import {
  resetUserPasswordThunk,
  updateUserLockThunk,
  updateUserLoginIdThunk,
} from '@redux/feature/user/userThunk';
import { debouncedURL } from '@lib/utils/debounceURL';
import { Status } from '@lib/constants/enum';
import { getUpdatedFields } from '@lib/utils/getUpdatedFields';

const AgentReferralManager = () => {
  const router = useRouter();
  const dispatch = useAppDispatch();
  const { agentReferralPartner, status } = useAppSelector(state => state.agentReferralPartner);
  const [selectedPartner, setSelectedPartner] = useState<IAgentReferralPartner | null>(null);
  const [actionType, setActionType] = useState<
    'add' | 'edit' | 'delete' | 'lock' | 'resetPassword' | 'resetLoginId' | null
  >(null);
  const [viewMode, setViewMode] = useState<'grid' | 'table'>('grid');
  const [resetForm] = Form.useForm();
  const [changeForm] = Form.useForm();
  const passwordAutoGenerated = Form.useWatch('passwordAutoGenerated', resetForm);
  const { debouncedUpdateURL, setParams, filters } = debouncedURL({
    filtersKey: ['search', 'status'],
    initialValue: {
      status: '',
    },
  });
  useEffect(() => {
    fetchAgentReferralData();
  }, [filters]);

  useEffect(() => {
    return () => {
      debouncedUpdateURL.cancel();
    };
  }, [debouncedUpdateURL]);

  const goToPartnerDetail = (partner: IAgentReferralPartner) => {
    router.push(`/agent-referral/${partner.agentReferralPartnerId}`);
  };

  const fetchAgentReferralData = async () => {
    try {
      const params = {
        search: filters?.search || undefined,
        is_active: filters?.status !== '' ? filters?.status === 'active' : undefined,
      };
      await dispatch(fetchAllAgentReferral(params)).unwrap();
    } catch (error) {
      message.error(error || 'Failed to fetch agent referral data');
    }
  };

  const handleAddPartner = async values => {
    try {
      if (!!selectedPartner) {
        const { isUpdated, updatedFields } = getUpdatedFields(values, selectedPartner);
        if (!isUpdated) {
          setActionType(null);
          setSelectedPartner(null);
          return;
        }
        await dispatch(
          updateAgentReferral({ data: updatedFields, id: selectedPartner.agentReferralPartnerId })
        ).unwrap();
        message.success('Agent referral partner updated successfully');
      } else {
        await dispatch(createAgentReferral(values)).unwrap();
        message.success('Agent referral partner added successfully');
      }
      setActionType(null);
      setSelectedPartner(null);
    } catch (error) {
      message.error(error || 'Failed to save partner');
    }
  };

  const handleDeleteConfirm = async () => {
    try {
      await dispatch(deleteAgentReferral(selectedPartner?.agentReferralPartnerId)).unwrap();
      message.success('Agent referral deleted successfully');
      setActionType(null);
      setSelectedPartner(null);
    } catch (error) {
      message.error(error || 'Failed to delete agent referral');
    }
  };

  const handleLockConfirm = async () => {
    try {
      await dispatch(
        updateUserLockThunk({
          id: selectedPartner?.user?.userId,
          type: 'agentReferral',
        })
      ).unwrap();
      message.success(
        willLock
          ? 'Agent referral partner locked successfully'
          : 'Agent referral partner unlocked successfully'
      );
      setActionType(null);
      setSelectedPartner(null);
    } catch (error) {
      message.error(
        error ||
          (willLock
            ? 'Failed to lock agent referral partner'
            : 'Failed to unlock agent referral partner')
      );
    }
  };

  const handleSaveResetPassword = async () => {
    const payload = await resetForm.validateFields();
    try {
      await dispatch(
        resetUserPasswordThunk({
          data: payload,
          id: selectedPartner?.user?.userId,
          type: 'agentReferral',
        })
      ).unwrap();
      message.success('Password reset successfully');
      setActionType(null);
      setSelectedPartner(null);
      resetForm.resetFields();
    } catch (error) {
      message.error(error || 'Failed to reset password');
    }
  };

  const handleChangeIdModal = async () => {
    const values = await changeForm.validateFields();
    try {
      await dispatch(
        updateUserLoginIdThunk({
          data: values,
          id: selectedPartner?.user?.userId,
          type: 'agentReferral',
        })
      ).unwrap();
      message.success('Login Id reset successfully');
      setActionType(null);
      setSelectedPartner(null);
    } catch (error) {
      message.error(error || 'Failed to reset loginId');
    }
  };

  const willLock = selectedPartner ? !(selectedPartner.user.isLocked ?? false) : false;

  return (
    <div className="p-4">
      <Typography.Title level={4}>Agent/Referral Partner Listing</Typography.Title>

      <AgentReferralHeader
        total={agentReferralPartner?.length}
        setParams={setParams}
        filters={filters}
        onViewChange={setViewMode}
        onCreateClick={() => {
          setActionType('add');
          setSelectedPartner(null);
        }}
      />

      {agentReferralPartner?.length === 0 ? (
        <Empty description="No Agents found." />
      ) : viewMode === 'grid' ? (
        <AgentReferralGrid
          partners={agentReferralPartner}
          onEdit={p => {
            setSelectedPartner(p);
            setActionType('add');
          }}
          onDelete={p => {
            setSelectedPartner(p);
            setActionType('delete');
          }}
          onLock={p => {
            setSelectedPartner(p);
            setActionType('lock');
          }}
          onResetPassword={p => {
            setSelectedPartner(p);
            setActionType('resetPassword');
          }}
          onViewDetails={goToPartnerDetail}
        />
      ) : (
        <AgentReferralTable
          partners={agentReferralPartner}
          onEdit={p => {
            setSelectedPartner(p);
            setActionType('add');
          }}
          onDelete={p => {
            setSelectedPartner(p);
            setActionType('delete');
          }}
          onRowClick={goToPartnerDetail}
          onResetPassword={p => {
            setSelectedPartner(p);
            setActionType('resetPassword');
          }}
          onLock={p => {
            setSelectedPartner(p);
            setActionType('lock');
          }}
        />
      )}

      {actionType === 'add' && (
        <PartnerDetailModal
          open={actionType === 'add'}
          initialData={selectedPartner || null}
          onClose={() => setActionType(null)}
          onSubmit={handleAddPartner}
          setActionType={setActionType}
          loading={status.create === Status.PENDING}
        />
      )}

      {actionType === 'delete' && selectedPartner && (
        <ConfirmationModal
          open={actionType === 'delete'}
          onClose={() => setActionType(null)}
          onConfirm={handleDeleteConfirm}
          message={`Delete ${selectedPartner?.user?.name}?`}
          type="danger"
          confirmText="Delete"
          loading={status.create === Status.PENDING}
        />
      )}

      {actionType === 'lock' && selectedPartner && (
        <ConfirmationModal
          open={actionType === 'lock'}
          onClose={() => setActionType(null)}
          onConfirm={handleLockConfirm}
          message={`Are you sure you want to ${willLock ? 'lock' : 'unlock'} this partner?`}
          type={willLock ? 'danger' : 'info'}
          confirmText={willLock ? 'Lock' : 'Unlock'}
          loading={status.create === Status.PENDING}
        />
      )}

      {actionType === 'resetPassword' && selectedPartner && (
        <Modal
          open={actionType === 'resetPassword'}
          onCancel={() => {
            setSelectedPartner(null);
            setActionType(null);
          }}
          centered
          title={`Reset Password - ${selectedPartner?.user?.name}`}
          okText="Save"
          onOk={handleSaveResetPassword}
          confirmLoading={status.create === Status.PENDING}
        >
          <div className="mt-2">
            <Form form={resetForm} layout="vertical">
              <div className="flex items-center gap-2 mb-2">
                <Form.Item name="passwordAutoGenerated" valuePropName="checked">
                  <Switch />
                </Form.Item>
                <span>Automatically generate password & email</span>
              </div>

              {!passwordAutoGenerated && (
                <>
                  <Row gutter={16}>
                    <Col span={12}>
                      <Form.Item
                        name="manualPassword"
                        label="Password"
                        rules={[{ required: true }]}
                      >
                        <Input.Password />
                      </Form.Item>
                    </Col>
                  </Row>

                  <div className="text-xs text-gray-500 ml-1 mb-2">
                    <p>Password must include:</p>
                    <p>• 8+ characters</p>
                    <p>• Upper & lower letters</p>
                    <p>• Number</p>
                    <p>• Special character [!@#$%^&*-]</p>
                  </div>

                  <div className="flex items-center gap-2 mb-2">
                    <Form.Item name="nextLoginPasswordChange" valuePropName="checked">
                      <Switch />
                    </Form.Item>
                    <span>Ask partner to change password at next login</span>
                  </div>

                  <div className="flex items-center gap-2 mb-2">
                    <Form.Item name="emailPassword" valuePropName="checked">
                      <Switch />
                    </Form.Item>
                    <span>Email the password</span>
                  </div>
                </>
              )}
            </Form>
          </div>
        </Modal>
      )}

      {actionType === 'resetLoginId' && selectedPartner && (
        <Modal
          open={actionType === 'resetLoginId'}
          onCancel={() => {
            setSelectedPartner(null);
            setActionType(null);
          }}
          onOk={() => {
            handleChangeIdModal();
          }}
          okText="Save"
          centered
          title="Change Login ID"
          confirmLoading={status.create === Status.PENDING}
        >
          <Form form={changeForm} layout="vertical">
            <Row gutter={16}>
              <Col span={12}>
                <Form.Item
                  name="newLoginId"
                  label="Login ID"
                  rules={[{ required: true }]}
                  initialValue={selectedPartner?.user?.loginId}
                >
                  <Input />
                </Form.Item>
                <Form.Item
                  name="emailLoginId"
                  label="Email Login Id"
                  valuePropName="checked"
                  initialValue={false}
                >
                  <Switch />
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Modal>
      )}
    </div>
  );
};

export default AgentReferralManager;
