const theme = {
  components: {
    Button: {
      colorPrimary: "var(--primary)",         
      colorPrimaryHover: "var(--primary-hover)", 
      colorPrimaryActive: "var(--primary)", 
      colorText: "var(--primary)",         
      colorTextHover: "var(--primary-hover)", 
      colorBorder: "var(--primary)",      
      colorBorderHover: "var(--primary-hover)",  
    },
    Input: {
      colorBgContainer: "var(--card-color)",
      colorText: "var(--font-color)",
      colorBorder: "var(--border-color)",
      colorPrimary: "var(--primary)",
      colorError: "var(--danger)",
      colorTextDisabled: "var(--font-color-100)",
      colorSuccess: "var(--success)",
      colorWarning: "var(--warning)",
      colorPlaceholder: "var(--font-color-100)",
      colorTextPlaceholder: "var(--font-color-100)",
    },
    Form: {
      labelColor: "var(--font-color-100)",
      labelFontSize: 14,
      labelHeight: 20,
      itemMarginBottom: 16,
    },
    InputNumber: {
      colorBgContainer: "var(--card-bg-primary)",
      colorText: "var(--font-color)",
      colorTextPlaceholder: "var(--text-secondary)",
      colorBorder: "var(--border-color)",
      activeBorderColor: "var(--primary-color)",
      hoverBorderColor: "var(--primary-color-hover)",
      colorBgContainerDisabled: "var(--bg-disabled)",
      colorTextDisabled: "var(--text-disabled)",
      handleBg: "var(--card-bg-secondary)",
      handleHoverColor: "var(--primary-color)",
      handleActiveBg: "var(--primary-color-hover)",
      handleDisabledBg: "var(--bg-disabled)",
      colorTextAddon: "var(--primary)",
    },
    Select: {
      colorBgContainer: "var(--card-color)",
      colorBorder: "var(--border-color)",
      colorText: "var(--font-color)",
      optionFontSize: 14,
      colorTextPlaceholder: "var(--font-color-100)",
      optionSelectedBg: "var(--primary-10)",
      optionSelectedColor: "var(--primary)",
      optionActiveBg: "var(--primary-10)",
      colorBgElevated: "var(--card-color)",
    },
    Radio: {
      colorPrimary: "var(--primary)",
      colorPrimaryHover: "var(--primary-100)",
      colorBorder: "var(--border-color)",
      colorBgContainer: "var(--card-color)",
      colorText: "var(--font-color)",
      controlOutline: "var(--primary)",
    },
    Checkbox: {
      colorPrimary: "var(--primary)",
      colorPrimaryHover: "var(--primary-hover)",
      colorBorder: "var(--border-color)",
      colorBgContainer: "var(--card-color)",
      colorText: "var(--font-color)",
      controlOutline: "var(--primary)",
    },
    Table: {
      headerBg: "var(--card-color)",
      headerColor: "var(--font-color)",
      headerBorderColor: "var(--border-color)",
      bodyBg: "var(--card-color)",
      rowHoverBg: "var(--primary-10)",
      rowSelectedBg: "var(--primary-10)",
      borderColor: "var(--border-color)",
      colorText: "var(--font-color-100)",
      colorBgContainer: "var(--card-color)",
      colorBgBase: "var(--body-color)",
      colorPrimary: "var(--primary)",
      colorFillAlter: "var(--primary-10)",
      headerSplitColor: "var(--border-color)",
    },
    Pagination: {
      colorPrimary: "var(--font-color-400)",
      colorPrimaryHover: "var(--primary-hover)",
      itemActiveBg: "var(--primary-100)",
      colorText: "var(--font-color-100)",
      colorTextDisabled: "var(--disabled-color)",
      itemBg: "var(--card-color)",
      itemInputBg: "var(--card-color)",
    },
    Modal: {
      contentBg: "var(--card-color)",
      headerBg: "var(--card-color)",
      headerColor: "var(--font-color)",
      footerBg: "var(--card-color)",
      titleColor: "var(--font-color)",
      titleFontSize: 24,
      colorText: "var(--font-color)",
      colorIcon: "var(--font-color)",
      colorIconHover: "var(--primary)",
      borderRadiusLG: 16,
    },
    Card: {
      colorBgContainer: "var(--card-color)",
      colorBorder: "var(--primary)",
      colorTextHeading: "var(--font-color)",
      colorText: "var(--font-color)",
      headerBg: "var(--card-color)",
      padding: 16,
    },
    Menu: {
      // Backgrounds
      colorBgContainer: "var(--card-color)",
      colorItemBg: "var(--card-color)",
      colorItemBgHover: "var(--primary-10)",
      colorItemBgSelected: "var(--primary-10)",

      // Text colors
      colorItemText: "var(--font-color)",
      colorItemTextHover: "var(--primary)",
      colorItemTextSelected: "var(--primary)",
      colorSubItemBg: "var(--card-color)",

      // Borders
      colorBorder: "var(--border-color)",
      activeBarBorderWidth: 2,
      activeBarBorderColor: "var(--primary)",

      // Font & sizing
      itemMarginInline: 8,
      itemMarginBlock: 4,
      itemBorderRadius: 8,
      itemHeight: 40,
      itemPaddingInline: 12,
      fontSize: 14,
    },
    Tabs: {
      colorText: "var(--font-color)",
      inkBarColor: "var(--primary)",
      itemHoverColor: "var(--primary)",
      itemSelectedColor: "var(--primary)",
      itemActiveColor: "var(--primary)",
    },
    Typography: {
      colorTextHeading: "var(--font-color)",
    },
    Collapse: {
      headerPadding: "12px 16px",
      contentPadding: "12px 16px",
      borderRadiusLG: 0,
      borderRadiusSM: 0,
      borderRadius: 0,
    },
    Result:{
      colorTextHeading:'var(--font-color)',
      colorTextDescription:'var(--font-color-100)'
    }
  },
};

export default theme;
