const theme = {
    components: {
      Button: {
        colorPrimary: 'var(--primary)',
        colorPrimaryHover: 'var(--primary-10)',
        colorText: 'var(--white)',
        colorBorder: 'var(--primary)',
        colorBgBase: 'var(--primary-10)',
      },
      Input: {
        colorBgContainer: 'var(--card-color)',
        colorText: 'var(--font-color)',
        colorBorder: 'var(--border-color)',
        colorPrimary: 'var(--primary)',
        colorError: 'var(--danger)',
        colorSuccess: 'var(--success)',
        colorWarning: 'var(--warning)',
        colorPlaceholder: 'var(--font-color-100)',
        colorTextPlaceholder: 'var(--font-color-100)',
      },
      Checkbox: {
        colorPrimary: 'var(--primary)',
        colorBgContainer: 'var(--card-color)',
        colorBorder: 'var(--border-color)',
        colorText: 'var(--font-color)',
      },
      Form: {
        labelColor: 'var(--font-color-100)',
        labelFontSize: 14,
        labelHeight: 20,
        itemMarginBottom: 16,
      },
      Select: {
        colorBgContainer: 'var(--card-color)',       
        colorBorder: 'var(--border-color)',         
        colorText: 'var(--font-color)',             
        optionFontSize: 14,
        colorTextPlaceholder: 'var(--font-color-100)',
        optionSelectedBg: 'var(--primary-10)',     
        optionSelectedColor: 'var(--primary)',     
        optionActiveBg: 'var(--primary-10)',       
        colorBgElevated: 'var(--card-color)', 
      },
      Radio: {
        colorPrimary: 'var(--primary)',         
        colorPrimaryHover: 'var(--primary-100)',
        colorBorder: 'var(--border-color)',     
        colorBgContainer: 'var(--card-color)',  
        colorText: 'var(--font-color)',         
        controlOutline: 'var(--primary)',       
      },
      Table: {
        headerBg: 'var(--card-color)',            
        headerColor: 'var(--font-color)',        
        headerBorderColor: 'var(--border-color)',
        bodyBg: 'var(--card-color)',
        rowHoverBg: 'var(--primary-10)',
        rowSelectedBg: 'var(--primary-10)',
        borderColor: 'var(--border-color)',
        colorText: 'var(--font-color-100)',      
        colorBgContainer: 'var(--card-color)',
        colorBgBase: 'var(--body-color)',
        colorPrimary: 'var(--primary)',
        colorFillAlter: 'var(--primary-10)',     
      },
      Modal: {
        contentBg: "var(--card-color)",       
        headerBg: "var(--card-color)",        
        headerColor: "var(--font-color)",     
        footerBg: "var(--card-color)",     
        titleColor: "var(--font-color)",   
        colorText: "var(--font-color)",    
        colorIcon: 'var(--font-color)',        
        colorIconHover: 'var(--primary)',      
        borderRadiusLG: 16,                   
      },
    },
  };
  
  export default theme;