import { Button, DatePicker, Drawer, Form, Input, message, Select, Switch, Upload } from 'antd';
import { useEffect, useState } from 'react';
import { useRoleHook } from '@hooks/useRoleHook';
import { useCountryHook } from '@hooks/useCountryHook';
import { useStateHook } from '@hooks/useStateHook';
import {
  addressLine1Rules,
  addressLine2Rules,
  cityRules,
  emailRules,
  nameRules,
  optionalPhoneRule,
  passwordRules,
  phoneRules,
  zipCodeRules,
} from '@lib/constants/formInputValidations';
import dayjs from 'dayjs';
import { useAppSelector } from '@hooks/redux';
import { Status } from '@lib/constants/enum';
import { IconEye, IconEyeOff } from '@tabler/icons-react';
export const UserFormDrawer = ({
  open,
  onCancel,
  onSubmit,
  resetPassword,
  setModalOpen,
  setDrawerOpen,
  isEditing,
  initialValue,
  type,
}) => {
  const { users, status } = useAppSelector(state => state.user);
  const [showPassword, setShowPassword] = useState<boolean>(false);
  const [showAdvancedDetails, setShowAdvancedDetails] = useState(false);
  const [showform, setShowForm] = useState(type === 'create');
  const [form] = Form.useForm();
  const companyAddress = Form.useWatch('useCompanyAddress', form);
  const passwordGenerate = Form.useWatch('passwordAutoGenerated', form);
  const roleId = Form.useWatch('roleId', form);
  const { roleOptions } = useRoleHook();
  const { countryOptions } = useCountryHook();
  const { stateOptions } = useStateHook();
  const userOptions = users
    .filter(user => user.roleId === roleId)
    .map(user => ({
      label: user.name,
      value: user.usersId,
    }));

  useEffect(() => {
    isEditing && form.setFieldsValue(initialValue);
  }, []);

  async function handleSubmit() {
    const values = await form.validateFields();
    showform ? onSubmit(values) : resetPassword(values);
  }
  return (
    <Drawer
      open={open}
      onClose={onCancel}
      title={
        <div className="flex justify-between items-center">
          <p>{showform ? 'Manage User' : 'Reset Password'}</p>

          {isEditing && showform && (
            <div className="flex gap-2">
              <Button type="primary" onClick={() => setShowForm(false)}>
                Reset Password
              </Button>
              <Button
                type="primary"
                onClick={() => {
                  setDrawerOpen(null);
                  setModalOpen('resetLoginId');
                }}
              >
                Change Login Id
              </Button>
            </div>
          )}
        </div>
      }
      width={700}
    >
      <Form
        form={form}
        layout="vertical"
        onFinish={handleSubmit}
        disabled={status.users.create === Status.PENDING}
      >
        {showform && (
          <>
            <div className="grid grid-cols-2 gap-3">
              <Form.Item label="Name" name="name" rules={nameRules}>
                <Input />
              </Form.Item>
              <Form.Item label="Email" name="email" rules={emailRules}>
                <Input />
              </Form.Item>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <Form.Item label="Phone" name="phone" rules={optionalPhoneRule}>
                <Input />
              </Form.Item>
              <Form.Item label="Login ID" name="loginId">
                <Input />
              </Form.Item>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <Form.Item label="Initials" name="initials">
                <Input />
              </Form.Item>
              {/* <Form.Item label="Select Builders" name="builders">
                <CustomBulkSelect
                  options={[
                    { label: 'My Home', value: 'My Home' },
                    { label: 'Home', value: 'Home' },
                  ]}
                  onChange={() => {}}
                />
              </Form.Item> */}
            </div>
            <Form.Item
              label="Role"
              name="roleId"
              rules={[{ required: true, message: 'Please Select Role' }]}
            >
              <Select placeholder="Select Role" options={roleOptions} />
            </Form.Item>
            <Form.Item label="Reporting To" name="reportingTo">
              <Select placeholder="Select User" options={userOptions} />
            </Form.Item>
            <div className="grid grid-cols-2 gap-3">
              <div className="flex place-items-start gap-2">
                <Form.Item name="useCompanyAddress" valuePropName="checked" initialValue={true}>
                  <Switch />
                </Form.Item>
                <p className="text-font-color-100">Use Company Address</p>
              </div>

              <p
                onClick={() => setShowAdvancedDetails(prev => !prev)}
                className="cursor-pointer text-blue"
              >
                {showAdvancedDetails ? 'Hide' : 'Show'} Advance Details
              </p>
            </div>
            {!companyAddress && (
              <>
                <div className="grid grid-cols-2 gap-3">
                  <Form.Item
                    label="Country"
                    name={['address', 'countryId']}
                    rules={[{ required: true, message: 'Please Select Country' }]}
                  >
                    <Select options={countryOptions} />
                  </Form.Item>
                  <Form.Item
                    label="State/Region"
                    name={['address', 'stateId']}
                    rules={[{ required: true, message: 'Please Select State/Region' }]}
                  >
                    <Select options={stateOptions} />
                  </Form.Item>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <Form.Item
                    label="Address1"
                    name={['address', 'addressLine1']}
                    rules={addressLine1Rules}
                  >
                    <Input />
                  </Form.Item>
                  <Form.Item
                    label="Address2"
                    name={['address', 'addressLine2']}
                    rules={addressLine2Rules}
                  >
                    <Input />
                  </Form.Item>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <Form.Item label="City/Suburb" name={['address', 'city']} rules={cityRules}>
                    <Input />
                  </Form.Item>
                  <Form.Item
                    label="Zip/Postal Code"
                    name={['address', 'zipCode']}
                    rules={zipCodeRules}
                  >
                    <Input />
                  </Form.Item>
                </div>
              </>
            )}
            {showAdvancedDetails && (
              <>
                <div className="grid grid-cols-2 gap-3">
                  <Form.Item
                    label="Date of Joining"
                    name="dateOfJoining"
                    getValueProps={value => ({ value: value ? dayjs(value) : null })}
                    getValueFromEvent={date => (date ? date.format('YYYY-MM-DD') : null)}
                    rules={[{ required: true, message: 'Please Select Joining Date' }]}
                  >
                    <DatePicker />
                  </Form.Item>
                  <Form.Item
                    label="Date of Birth"
                    name="dateOfBirth"
                    getValueProps={value => ({ value: value ? dayjs(value) : null })}
                    getValueFromEvent={date => (date ? date.format('YYYY-MM-DD') : null)}
                    rules={[{ required: true, message: 'Please Select Date of Birth' }]}
                  >
                    <DatePicker />
                  </Form.Item>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <Form.Item label="Designation" name="designation">
                    <Input />
                  </Form.Item>
                  <Form.Item label="Secondary Phone" name="secondaryPhone" rules={phoneRules}>
                    <Input />
                  </Form.Item>
                </div>
                <Form.Item label="Remarks" name="remark">
                  <Input />
                </Form.Item>
                <Form.Item label="Consultant Bio" name="consultantBio">
                  <Input />
                </Form.Item>
                <div className="grid grid-cols-2 gap-3">
                  <Form.Item
                    label="Photo"
                    name="photo"
                    getValueFromEvent={e => {
                      if (e && e.fileList) {
                        return e.fileList;
                      }
                      return [];
                    }}
                  >
                    <Upload accept=".png,.jpg,.jpeg">
                      <Button>Click To Upload</Button>
                    </Upload>
                  </Form.Item>
                  <Form.Item
                    label="Signature"
                    name="signature"
                    getValueFromEvent={e => {
                      if (e && e.fileList) {
                        return e.fileList;
                      }
                      return [];
                    }}
                  >
                    <Upload accept=".png,.jpg,.jpeg">
                      <Button>Click To Upload</Button>
                    </Upload>
                  </Form.Item>
                </div>
              </>
            )}
          </>
        )}

        {(!isEditing || !showform) && (
          <>
            <div className="flex place-items-start gap-2">
              <Form.Item name="passwordAutoGenerated" valuePropName="checked">
                <Switch />
              </Form.Item>
              <div className="space-y-1">
                <p className="text-font-color-100">
                  Automatically generate a password and send an email to the user
                </p>
                {!passwordGenerate && (
                  <>
                    <Form.Item name="manualPassword" rules={passwordRules}>
                      <Input
                        type={showPassword ? 'text' : 'password'}
                        suffix={
                          <span
                            onClick={() => setShowPassword(!showPassword)}
                            className="cursor-pointer text-font-color-100"
                          >
                            {showPassword ? <IconEyeOff /> : <IconEye />}
                          </span>
                        }
                      />
                    </Form.Item>
                    <p className="text-sm text-font-color-100">Your password must have : </p>
                    <div className=" text-font-color-400">
                      <p>8 or more characters</p>
                      <p>Upper and Lower letters</p>
                      <p>At least one number</p>
                      <p>At least one special character [! @ # $ % ^ & * -]</p>
                    </div>
                  </>
                )}
              </div>
            </div>
            {!passwordGenerate && (
              <>
                <div className="flex place-items-start gap-2 mt-1">
                  <Form.Item name="nextLoginPasswordChange" valuePropName="checked">
                    <Switch />
                  </Form.Item>
                  <p className="text-font-color-100">Ask for a password change at the next login</p>
                </div>
                <div className="flex place-items-start gap-2">
                  <Form.Item name="emailLoginCredentials" valuePropName="checked">
                    <Switch />
                  </Form.Item>
                  <p className="text-font-color-100">Email the Password</p>
                </div>
              </>
            )}
          </>
        )}

        <div className="flex gap-2 justify-end">
          <Button
            onClick={() => {
              showform ? onCancel() : setShowForm(true);
            }}
            disabled={status.users.create === Status.PENDING}
          >
            Cancel
          </Button>
          <Button
            type="primary"
            htmlType="submit"
            loading={status.users.create === Status.PENDING}
            disabled={status.users.create === Status.PENDING}
          >
            Save
          </Button>
        </div>
      </Form>
    </Drawer>
  );
};
