import { exportToExcel } from '@lib/utils/exportToExcel';

export const MaintenanceDetailedReport = () => {
    const data = [
        {
            ReferenceID: 'MYH00655-MR1',
            CustomerName: 'Grand Homes Demo',
            JobAddress: '234, fall street, epping, VIC, 1234',
            StartDate: '',
            EndDate: '',
            CompletedTask: '',
            PendingTask: '',
            Supplier: '',
            Supervisor: 'Murthy Muthuswamy',
            RequestStatus: 'Pending',
            NoOfTask: '1',
            Notes: '',
        },
        {
            ReferenceID: 'MYH00131-MR15',
            CustomerName: 'Mr and Mrs Smith',
            JobAddress: 'Lot 1234, Tarneit, VIC, 3030',
            StartDate: '',
            EndDate: '',
            CompletedTask: '',
            PendingTask: '',
            Supplier: '',
            Supervisor: 'Murthy Muthuswamy',
            RequestStatus: 'Pending',
            NoOfTask: '3',
            Notes: '',
        },
        {
            ReferenceID: 'MYH00131-MR14',
            CustomerName: 'Mr and Mrs Smith',
            JobAddress: 'Lot 1234, Tarneit, VIC, 3030',
            StartDate: '',
            EndDate: '',
            CompletedTask: '',
            PendingTask: '',
            Supplier: '',
            Supervisor: 'Murthy Muthuswamy',
            RequestStatus: 'Pending',
            NoOfTask: '1',
            Notes: '',
        },
        {
            ReferenceID: 'MYH00638-MR2',
            CustomerName: 'Soundarya',
            JobAddress: '14, Melbourne view, Sydney, VIC, 3024',
            StartDate: '',
            EndDate: '',
            CompletedTask: '',
            PendingTask: '',
            Supplier: '',
            Supervisor: 'Murthy Muthuswamy',
            RequestStatus: 'Pending',
            NoOfTask: '1',
            Notes: '',
        },
        {
            ReferenceID: 'MYH00638-MR1',
            CustomerName: 'Soundarya',
            JobAddress: '14, Melbourne view, Sydney, VIC, 3024',
            StartDate: '',
            EndDate: '',
            CompletedTask: '',
            PendingTask: '',
            Supplier: '',
            Supervisor: 'Murthy Muthuswamy',
            RequestStatus: 'Completed',
            NoOfTask: '1',
            Notes: '',
        },
        {
            ReferenceID: 'MYH00131-MR13',
            CustomerName: 'Mr and Mrs Smith',
            JobAddress: 'Lot 1234, Tarneit, VIC, 3030',
            StartDate: '',
            EndDate: '',
            CompletedTask: '',
            PendingTask: '',
            Supplier: '',
            Supervisor: 'Murthy Muthuswamy',
            RequestStatus: 'Pending',
            NoOfTask: '2',
            Notes: '',
        },
    ];
    const column = {
        ReferenceID: { label: 'Reference ID', color: 'FF0023BD' },
        CustomerName: { label: 'Customer Name', color: 'FF0023BD' },
        JobAddress: { label: 'Job Address', color: 'FF0023BD' },
        StartDate: { label: 'Start Date', color: 'FF0023BD' },
        EndDate: { label: 'End Date', color: 'FF0023BD' },
        CompletedTask: { label: 'Completed Task', color: 'FF0023BD' },
        PendingTask: { label: 'Pending Task', color: 'FF0023BD' },
        Supplier: { label: 'Supplier', color: 'FF0023BD' },
        Supervisor: { label: 'Supervisor', color: 'FF0023BD' },
        RequestStatus: { label: 'Request Status', color: 'FF0023BD' },
        NoOfTask: { label: 'No of Task', color: 'FF0023BD' },
        Notes: { label: 'Notes', color: 'FF0023BD' },
    };

    exportToExcel({
        data: data,
        fileName: 'Maintenance Detailed Report',
        sheetName: 'Maintenance Detailed Report',
        columnHeaders: column,
        title: 'Maintenance Detailed Report',
        extraHeaderRows: [
            {
                columnHeaders: {
                    DateOfExport: { label: 'Date of Export', color: 'FF0023BD' },
                },
                data: [
                    {
                        DateOfExport: '25-08-2025',
                    },
                ],
                layout: 'vertical',
                position: 'top',
            },
        ],
    });
};
