import { exportToExcel } from '@lib/utils/exportToExcel';

export const FloorPlanFacadeReport = () => {
    const data = [
        {
            ReferenceID: 'MYH00663',
            LeadStatus: 'Closed Won',
            Deposited: 'Deposited',
            CustomerName: 'Mathew',
            JobAddress: 'Lot 34 Chelsea Street, Tarneit, VIC, 3029',
            QuotationID: 'MYH25090081',
            QuotationStatus: 'Approved',
            FloorPlan: 'Rose 27',
            Facade: 'LKL 81',
            DwellingType: 'Single Storey',
            Label: '',
            Assignee: 'Murthy Muthuswamy',
        },
        {
            ReferenceID: 'MYH00660',
            LeadStatus: 'Closed Won',
            Deposited: 'Deposited',
            CustomerName: 'Mathew',
            JobAddress: 'Lot 333 ABC Street, Cobblebank, VIC, 3338',
            QuotationID: 'MYH25090076',
            QuotationStatus: 'Approved',
            FloorPlan: 'My Home 1',
            Facade: 'LKL 81',
            DwellingType: 'Single Storey',
            Label: '',
            Assignee: 'Murthy Muthuswamy',
        },
        {
            ReferenceID: 'MYH00657',
            LeadStatus: 'Closed Won',
            Deposited: 'Deposited',
            CustomerName: 'Mat',
            JobAddress: 'Lot 67 Melbourne Rd, Epping, VIC, 3030',
            QuotationID: 'MYH25090074',
            QuotationStatus: 'Approved',
            FloorPlan: 'My choice',
            Facade: 'Geo 25',
            DwellingType: 'Single Storey',
            Label: 'Standard',
            Assignee: 'Murthy Muthuswamy',
        },
        {
            ReferenceID: 'MYH00655',
            LeadStatus: 'Closed Won',
            Deposited: 'Deposited',
            CustomerName: 'Grand Homes Demo',
            JobAddress: '234, fall street, epping, VIC, 1234',
            QuotationID: 'MYH25080065',
            QuotationStatus: 'Approved',
            FloorPlan: 'My Home 1',
            Facade: 'A Mind Rock',
            DwellingType: 'Single Storey',
            Label: 'Premium',
            Assignee: 'Murthy Muthuswamy',
        },
        {
            ReferenceID: 'MYH00653',
            LeadStatus: 'Closed Won',
            Deposited: 'Deposited',
            CustomerName: 'Balram Test',
            JobAddress: '123, epping street, Melbourne, VIC, 1245',
            QuotationID: 'MYH25080064',
            QuotationStatus: 'Modified',
            FloorPlan: 'My Home 2',
            Facade: 'Tarneit 26',
            DwellingType: 'Single Storey',
            Label: '',
            Assignee: 'Murthy Muthuswamy',
        },
        {
            ReferenceID: 'MYH00650',
            LeadStatus: 'Closed Won',
            Deposited: 'Deposited',
            CustomerName: 'Demo lead',
            JobAddress: '123, office street, melbourne, VIC, 1233',
            QuotationID: 'MYH25070055',
            QuotationStatus: 'Approved',
            FloorPlan: 'My Home 1',
            Facade: 'A Mind Rock',
            DwellingType: 'Single Storey',
            Label: 'Premium',
            Assignee: 'Murthy Muthuswamy',
        },
        {
            ReferenceID: 'MYH00598',
            LeadStatus: 'Closed Won',
            Deposited: 'Deposited',
            CustomerName: 'Abdul Rahman',
            JobAddress: 'Lot 20 Devis Road, Mount Cottrell, VIC, 3024',
            QuotationID: 'MYH24100078',
            QuotationStatus: 'Modified',
            FloorPlan: 'My Home 1',
            Facade: 'A Mind Rock',
            DwellingType: 'Single Storey',
            Label: 'Premium',
            Assignee: 'Murthy Muthuswamy',
        },
    ];

    const column = {
        ReferenceID: { label: 'Reference ID', color: 'FF050980' },
        LeadStatus: {
            label: 'Lead Status',
            color: 'FF050980',
            dataColorFn: (value: string) => (value === 'Closed Won' ? 'FF28A745' : 'FF050980'),
        },
        Deposited: {
            label: 'Deposited',
            color: 'FF050980',
            dataColorFn: (value: string) => (value === 'Deposited' ? 'FF28A745' : 'FF050980'),
        },
        CustomerName: { label: 'Customer Name', color: 'FF050980' },
        JobAddress: { label: 'Job Address', color: 'FF050980' },
        QuotationID: { label: 'Quotation ID', color: 'FF050980' },
        QuotationStatus: {
            label: 'Quotation Status',
            color: 'FF050980',
            dataColorFn: (value: string) =>
                value === 'Approved' ? 'FF28A745' : value === 'Modified' ? 'FF007BFF' : 'FF050980',
        },
        FloorPlan: { label: 'Floor Plan', color: 'FF050980' },
        Facade: { label: 'Facade', color: 'FF050980' },
        DwellingType: {
            label: 'Dwelling Type',
            color: 'FF050980',
            dataColorFn: (value: string) => (value === 'Single Storey' ? 'FFF05AD0' : 'FF050980'),
        },
        Label: { label: 'Label', color: 'FF050980', dataColor: 'FF5C6BC0' },
        Assignee: { label: 'Assignee', color: 'FF050980' },
    };

    exportToExcel({
        data: data,
        fileName: 'My Home _ Floor Plan report',
        sheetName: 'My Home _ Floor Plan report',
        columnHeaders: column,
        title: "My Home _ Floor Plan Report"
    });
    exportToExcel({
        data: data,
        fileName: 'My Home_ Facade report',
        sheetName: 'My Home_ Facade report',
        columnHeaders: column,
        title: "My Home _ Facade Report"
    });
};
