import { exportToExcel } from '@lib/utils/exportToExcel';

export const LeadFocusReport = () => {
    const data = [
        {
            ReferenceID: 'MYH00665',
            Name: 'Joshua Ewinggg',
            ContactNo: '09876543211',
            Email: 'doca@mailinator.com',
            Created: '01-10-2025',
            Updated: '02-10-2025',
            PropertyAddress: '91 Hague L In numquam proident, Ex qui quia aut aute, VIC, 2075',
            DwellingType: 'Single Storey',
            LeadSource: 'Website',
            ReferralPartner: '',
            Rating: '',
            Status: 'Closed Won',
            LostReason: '',
            ClosedDate: '01-10-2025',
            Category: 'Opportunity',
            Land: '',
            Finance: '',
            FaceToFace: '',
            Purpose: '',
            ClientType: '',
            Deposit: 'Yes',
            DepositDate: '01-10-2025',
            ForecastDate: '',
            Packages: '02 Oct 25',
            Appointments: '',
            LastUpdatedOn: '',
            BudgetBuild: '',
            Region: '',
            PrelimAgreementSigned: '',
            ClientProfile: '',
            BudgetHL: '',
        },

        {
            ReferenceID: 'MYH00664',
            Name: 'john wick',
            ContactNo: '01234567823',
            Email: 'johnwick@gmail.com',
            Created: '01-10-2025',
            Updated: '01-10-2025',
            PropertyAddress: 'Lot 89, 09 In numquam proident, Ex qui quia aut aute, VIC, 2075',
            DwellingType: 'Double Storey',
            LeadSource: 'Website',
            ReferralPartner: '',
            Rating: 'Cold',
            Status: 'Closed Won',
            LostReason: '',
            ClosedDate: '01-10-2025',
            Category: 'Opportunity',
            Land: 'Yes',
            Finance: 'No',
            FaceToFace: 'Yes',
            Purpose: 'Own House',
            ClientType: 'First Home Buyer',
            Deposit: 'Yes',
            DepositDate: '01-10-2025',
            ForecastDate: '08-10-2025',
            Packages: 'Premium Pack woth $1000',
            Appointments: '01 Oct 25',
            LastUpdatedOn: '',
            BudgetBuild: '',
            Region: 'Sydney East',
            PrelimAgreementSigned: '',
            ClientProfile: '',
            BudgetHL: '',
        },

        {
            ReferenceID: 'MYH00663',
            Name: 'Mathew',
            ContactNo: '0406343244',
            Email: 'ms@insimplify.com.au',
            Created: '30-09-2025',
            Updated: '30-09-2025',
            PropertyAddress: 'Lot 34 Chelsea Street, Tarneit, VIC, 3029',
            DwellingType: 'Single Storey',
            LeadSource: 'REA',
            ReferralPartner: '',
            Rating: 'Hot',
            Status: 'Closed Won',
            LostReason: '',
            ClosedDate: '30-09-2025',
            Category: 'Opportunity',
            Land: '',
            Finance: '',
            FaceToFace: '',
            Purpose: '',
            ClientType: '',
            Deposit: 'Yes',
            DepositDate: '30-09-2025',
            ForecastDate: '',
            Packages: '30 Sep 25',
            Appointments: '',
            LastUpdatedOn: '',
            BudgetBuild: '',
            Region: 'Melbourne North',
            PrelimAgreementSigned: '',
            ClientProfile: '',
            BudgetHL: '',
        },

        {
            ReferenceID: 'MYH00662',
            Name: 'Johnathan',
            ContactNo: '02343434324',
            Email: 'john@gmail.com',
            Created: '22-09-2025',
            Updated: '30-09-2025',
            PropertyAddress: '208 Second Harum proident at n, Fugiat excepturi exe, VIC, 5021',
            DwellingType: 'Double Storey',
            LeadSource: 'Referral Partner',
            ReferralPartner: '',
            Rating: '',
            Status: 'Open',
            LostReason: '',
            ClosedDate: '',
            Category: 'Lead',
            Land: '',
            Finance: '',
            FaceToFace: '',
            Purpose: '',
            ClientType: '',
            Deposit: 'No',
            DepositDate: '',
            ForecastDate: '',
            Packages: 'Premium Pack woth $1000',
            Appointments: '30 Sep 25',
            LastUpdatedOn: '',
            BudgetBuild: '',
            Region: '',
            PrelimAgreementSigned: '',
            ClientProfile: '',
            BudgetHL: '',
        },

        {
            ReferenceID: 'MYH00661',
            Name: 'sunny',
            ContactNo: '03434545656',
            Email: 'sunnysingh@gmail.com',
            Created: '22-09-2025',
            Updated: '29-09-2025',
            PropertyAddress: '123 George Street, Sydney, VIC, 2000',
            DwellingType: 'Double Storey',
            LeadSource: 'Internal',
            ReferralPartner: '',
            Rating: '',
            Status: 'Closed Won',
            LostReason: '',
            ClosedDate: '29-09-2025',
            Category: 'Opportunity',
            Land: '',
            Finance: '',
            FaceToFace: '',
            Purpose: '',
            ClientType: '',
            Deposit: 'No',
            DepositDate: '',
            ForecastDate: '',
            Packages: 'Premium Pack woth $1000',
            Appointments: '29 Sep 25',
            LastUpdatedOn: '',
            BudgetBuild: '',
            Region: '',
            PrelimAgreementSigned: '',
            ClientProfile: '',
            BudgetHL: '',
        },

        {
            ReferenceID: 'MYH00660',
            Name: 'Mathew',
            ContactNo: '04061345667',
            Email: 'mathew@gmail.com',
            Created: '22-09-2025',
            Updated: '22-09-2025',
            PropertyAddress: 'Lot 333 ABC Street, Cobblebank, VIC, 3338',
            DwellingType: 'Single Storey',
            LeadSource: 'Referral Partner',
            ReferralPartner: 'Adam',
            Rating: 'Hot',
            Status: 'Closed Won',
            LostReason: '',
            ClosedDate: '22-09-2025',
            Category: 'Opportunity',
            Land: '',
            Finance: '',
            FaceToFace: '',
            Purpose: '',
            ClientType: '',
            Deposit: 'Yes',
            DepositDate: '22-09-2025',
            ForecastDate: '08-10-2025',
            Packages: '',
            Appointments: '22 Sep 25',
            LastUpdatedOn: '',
            BudgetBuild: '',
            Region: 'Melbourne West',
            PrelimAgreementSigned: '',
            ClientProfile: '',
            BudgetHL: '',
        },

        {
            ReferenceID: 'MYH00659',
            Name: 'Brad',
            ContactNo: '05678345',
            Email: 'brad@Citihomes.com.au',
            Created: '03-09-2025',
            Updated: '10-09-2025',
            PropertyAddress: 'Lot 223 Sayers Road, Tarneit, VIC, 3029',
            DwellingType: 'Single Storey',
            LeadSource: 'Internal',
            ReferralPartner: '',
            Rating: '',
            Status: 'Closed Won',
            LostReason: '',
            ClosedDate: '03-09-2025',
            Category: 'Opportunity',
            Land: '',
            Finance: '',
            FaceToFace: '',
            Purpose: '',
            ClientType: '',
            Deposit: 'Yes',
            DepositDate: '03-09-2025',
            ForecastDate: '',
            Packages: '10 Sep 25',
            Appointments: '',
            LastUpdatedOn: '',
            BudgetBuild: '',
            Region: '',
            PrelimAgreementSigned: '',
            ClientProfile: '',
            BudgetHL: '',
        },
    ];

    const column = {
        ReferenceID: { label: 'Reference ID', color: 'FF050980' },
        Name: { label: 'Name', color: 'FF050980' },
        ContactNo: { label: 'Contact', color: 'FF050980' },
        Email: { label: 'Email', color: 'FF050980' },
        Created: { label: 'Created', color: 'FF050980' },
        Updated: { label: 'Updated', color: 'FF050980' },
        PropertyAddress: { label: 'Property Address', color: 'FF050980' },
        DwellingType: { label: 'Dwelling Type', color: 'FF050980' },
        LeadSource: { label: 'Lead Source', color: 'FF050980' },
        ReferralPartner: { label: 'Referral Partner', color: 'FF050980' },
        Rating: { label: 'Rating', color: 'FF050980' },
        Status: { label: 'Status', color: 'FF050980' },
        LostReason: { label: 'Lost Reason', color: 'FF050980' },
        ClosedDate: { label: 'Closed Date', color: 'FF050980' },
        Category: { label: 'Category', color: 'FF050980' },
        Land: { label: 'Land', color: 'FF050980' },
        Finance: { label: 'Finance', color: 'FF050980' },
        FaceToFace: { label: 'Face to Face', color: 'FF050980' },
        Purpose: { label: 'Purpose', color: 'FF050980' },
        ClientType: { label: 'Client Type', color: 'FF050980' },
        Deposit: { label: 'Deposit', color: 'FF050980' },
        DepositDate: { label: 'Deposit Date', color: 'FF050980' },
        ForecastDate: { label: 'Forecast Date', color: 'FF050980' },
        Packages: { label: 'Packages', color: 'FF050980' },
        Appointments: { label: 'Appointments', color: 'FF050980' },
        LastUpdatedOn: { label: 'LastUpdatedOn', color: 'FF050980' },
        BudgetBuild: { label: 'Budget (Build)', color: 'FF050980' },
        Region: { label: 'Region', color: 'FF050980' },
        PrelimAgreementSigned: { label: 'Prelim Agreement Signed', color: 'FF050980' },
        ClientProfile: { label: 'Client Profile', color: 'FF050980' },
        BudgetHL: { label: 'Budget (H&L)', color: 'FF050980' },
    };

    exportToExcel({
        data: data,
        fileName: 'My Home_FocusReport',
        sheetName: 'My Home_FocusReport',
        columnHeaders: column,
    });
};
