import { exportToExcel } from '@lib/utils/exportToExcel';

export const QuotationReport = () => {
    const data = [
        {
            ReferenceID: 'MYH25100084',
            LeadJobRefID: 'MYH00665',
            Name: 'Joshua Ewing',
            Phone: '9876543211',
            Email: 'doca@mailinator.com',
            LeadSource: 'Website',
            CreatedDate: '01-10-2025',
            LatestApprovedDate: '30-10-2025',
            ContactAddress: 'In numquam proident, Ex qui quia aut aute, VIC, 2075',
            PropertyAddress: '91 Hague L In numquam proident, Ex qui quia aut aute, VIC, 2075',
            TotalCost: '200,000',
            DwellingType: 'Single Storey',
            Estate: 'Yoshi Witt',
            LandTitleDate: '01-10-2025',
            Assignee: 'Kishan',
            ReportingManager: 'Murthy Muthuswamy',
            Location: '',
            Label: '',
            Status: 'Approved',
            FirstApprovedDate: '30-10-2025',
        },
        {
            ReferenceID: 'MYH25100083',
            LeadJobRefID: 'MYH00664',
            Name: 'john wick',
            Phone: '1234567823',
            Email: 'johnwick@gmail.com',
            LeadSource: 'Website',
            CreatedDate: '01-10-2025',
            LatestApprovedDate: '01-10-2025',
            ContactAddress: 'asdfg, sydny, VIC, 30003',
            PropertyAddress: 'Lot 89, 09 In numquam proident, Ex qui quia aut aute, VIC, 2075',
            TotalCost: '37,400',
            DwellingType: 'Double Storey',
            Estate: 'Yoshi Witt',
            LandTitleDate: '',
            Assignee: 'Kishan',
            ReportingManager: 'Murthy Muthuswamy',
            Location: 'Sydney',
            Label: 'Premium',
            Status: 'Approved',
            FirstApprovedDate: '01-10-2025',
        },
        {
            ReferenceID: 'MYH25090081',
            LeadJobRefID: 'MYH00663',
            Name: 'Mathew',
            Phone: '406343244',
            Email: 'ms@insimplify.com.au',
            LeadSource: 'REA',
            CreatedDate: '30-09-2025',
            LatestApprovedDate: '30-09-2025',
            ContactAddress: '345 Sayers Road, Tarneit, VIC, 3029',
            PropertyAddress: 'Lot 34 Chelsea Street, Tarneit, VIC, 3029',
            TotalCost: '468,980',
            DwellingType: 'Single Storey',
            Estate: '',
            LandTitleDate: '',
            Assignee: 'Murthy Muthuswamy',
            ReportingManager: 'Murthy Muthuswamy',
            Location: '',
            Label: '',
            Status: 'Approved',
            FirstApprovedDate: '30-09-2025',
        },
        {
            ReferenceID: 'MYH25090080',
            LeadJobRefID: 'MYH00662',
            Name: 'Johnathan Whitney Castillo',
            Phone: '2343434324',
            Email: 'john@gmail.com',
            LeadSource: 'Referral Partner',
            CreatedDate: '29-09-2025',
            LatestApprovedDate: '30-09-2025',
            ContactAddress: '208 Second Court, Harum proident at n, Fugiat excepturi exe, VIC, 5021',
            PropertyAddress: '208 Second Harum proident at n, Fugiat excepturi exe, VIC, 5021',
            TotalCost: '1,236,385',
            DwellingType: 'Double Storey',
            Estate: 'Wade Evans',
            LandTitleDate: '',
            Assignee: 'Murthy Muthuswamy',
            ReportingManager: 'Murthy Muthuswamy',
            Location: 'Sydney',
            Label: 'Premium',
            Status: 'Approved',
            FirstApprovedDate: '30-09-2025',
        },
        {
            ReferenceID: 'MYH25090079',
            LeadJobRefID: 'MYH00661',
            Name: 'sunny',
            Phone: '3434545656',
            Email: 'sunnysingh@gmail.com',
            LeadSource: 'Internal',
            CreatedDate: '29-09-2025',
            LatestApprovedDate: '29-09-2025',
            ContactAddress: '123 George Street, Sydney, VIC, 2000',
            PropertyAddress: '123 George Street, Sydney, VIC, 2000',
            TotalCost: '1,248,385',
            DwellingType: 'Double Storey',
            Estate: '',
            LandTitleDate: '',
            Assignee: 'Murthy Muthuswamy',
            ReportingManager: 'Murthy Muthuswamy',
            Location: '',
            Label: 'Premium',
            Status: 'Approved',
            FirstApprovedDate: '29-09-2025',
        },
        {
            ReferenceID: 'MYH25090078',
            LeadJobRefID: 'MYH00637',
            Name: 'John Wick',
            Phone: '0406 166 577',
            Email: 'hello@aluxhomes.com.au',
            LeadSource: 'Referral Partner',
            CreatedDate: '24-09-2025',
            LatestApprovedDate: '24-09-2025',
            ContactAddress: 'Suite 10, 45 Tallis Circuit, Truganina, VIC, 3029',
            PropertyAddress: 'Suite 10, 45 Tallis Circuit, Truganina, VIC, 3029',
            TotalCost: '614,100',
            DwellingType: 'Single Storey',
            Estate: '',
            LandTitleDate: '',
            Assignee: 'Murthy Muthuswamy',
            ReportingManager: 'Murthy Muthuswamy',
            Location: '',
            Label: '',
            Status: 'Approved',
            FirstApprovedDate: '24-09-2025',
        },
    ];

    const column = {
        ReferenceID: { label: 'Reference ID', color: 'FF050980' },
        LeadJobRefID: { label: 'Lead/Job Ref ID', color: 'FF050980' },
        Name: { label: 'Name', color: 'FF050980' },
        Phone: { label: 'Phone', color: 'FF050980' },
        Email: { label: 'Email', color: 'FF050980' },
        LeadSource: { label: 'Lead Source', color: 'FF050980' },
        CreatedDate: { label: 'Created Date', color: 'FF050980' },
        LatestApprovedDate: { label: 'Latest Approved Date', color: 'FF050980' },
        ContactAddress: { label: 'Contact Address', color: 'FF050980' },
        PropertyAddress: { label: 'Property Address', color: 'FF050980' },
        TotalCost: { label: 'Total Cost $', color: 'FF050980' },
        DwellingType: { label: 'Dwelling Type', color: 'FF050980' },
        Estate: { label: 'Estate', color: 'FF050980' },
        LandTitleDate: { label: 'Land Title Date', color: 'FF050980' },
        Assignee: { label: 'Assignee', color: 'FF050980' },
        ReportingManager: { label: 'Reporting Manager', color: 'FF050980' },
        Location: { label: 'Location', color: 'FF050980' },
        Label: { label: 'Label', color: 'FF050980' },
        Status: { label: 'Status', color: 'FF050980' },
        FirstApprovedDate: { label: 'First Approved Date', color: 'FF050980' },
    };

    exportToExcel({
        data: data,
        fileName: 'My Home_QuotationReport',
        sheetName: 'My Home_QuotationReport',
        columnHeaders: column,
        title: "Quotation Report"

    });
};
