'use client';
import React, { useEffect } from 'react';
import { Modal, Form, Input, Row, Col, Select, Radio, Typography, Button, Switch } from 'antd';
import { useCountryHook } from '@hooks/useCountryHook';
import { useStateHook } from '@hooks/useStateHook';
import { useUsersHook } from '@hooks/useUserHook';
import { IAgentReferralPartner } from '@redux/feature/agentReferral/IAgentReferralState';

const { Title, Text } = Typography;

interface Props {
  open: boolean;
  onClose: () => void;
  onSubmit: (values: IAgentReferralPartner) => void;
  initialData?: IAgentReferralPartner;
  setActionType?: (
    action: 'add' | 'edit' | 'delete' | 'lock' | 'resetPassword' | 'resetLoginId' | null
  ) => void;
  loading?: boolean;
}

const PartnerDetailModal = ({
  open,
  onClose,
  onSubmit,
  initialData,
  setActionType,
  loading = false,
}: Props) => {
  const [form] = Form.useForm();
  const { countryOptions } = useCountryHook();
  const { stateOptions } = useStateHook();
  const { userOptions } = useUsersHook();
  const hasLogin = initialData?.user.loginId ? true : false;
  const passwordAutoGenerated = Form.useWatch(['user', 'passwordAutoGenerated'], form);
  const createLogin = Form.useWatch(['user', 'createLogin'], form);

  useEffect(() => {
    if (!!initialData) {
      form.setFieldsValue(initialData);
    }
  }, [initialData]);

  const handleSave = async () => {
    const values = await form.validateFields();
    onSubmit(values);
  };

  return (
    <>
      <Modal
        open={open}
        onCancel={onClose}
        width={950}
        okText="Save"
        onOk={handleSave}
        confirmLoading={loading}
      >
        <div className="flex items-center mb-4 gap-[10%]">
          <Title level={4} className="!mb-0">
            Agent/Referral Partner Details
          </Title>
          {hasLogin && (
            <div className="flex gap-2 mr-6">
              <Button
                type="primary"
                onClick={() => {
                  setActionType('resetPassword');
                }}
              >
                Reset Password
              </Button>
              <Button
                type="primary"
                onClick={() => {
                  setActionType('resetLoginId');
                }}
              >
                Change Login ID
              </Button>
            </div>
          )}
        </div>

        <div className="h-[60vh] overflow-y-auto pr-2 custom-scrollbar">
          <Form layout="vertical" form={form} initialValues={initialData}>
            <Row gutter={16}>
              {/* Personal Info */}
              <Col span={8}>
                <Form.Item name={['user', 'name']} label="Name" rules={[{ required: true }]}>
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item name={['user', 'email']} label="Email" rules={[{ required: true }]}>
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item name={['user', 'phone']} label="Phone" rules={[{ required: true }]}>
                  <Input />
                </Form.Item>
              </Col>

              {/* Address */}
              <Col span={8}>
                <Form.Item name={['address', 'countryId']} label="Country">
                  <Select options={countryOptions} />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item
                  name={['address', 'addressLine1']}
                  label="Address1"
                  rules={[{ required: true }]}
                >
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item name={['address', 'addressLine2']} label="Address2">
                  <Input />
                </Form.Item>
              </Col>

              <Col span={8}>
                <Form.Item name={['address', 'city']} label="City/Suburb">
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item name={['address', 'stateId']} label="State/Region">
                  <Select options={stateOptions} />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item
                  name={['address', 'zipCode']}
                  label="Zip / Postal Code"
                  rules={[{ required: true }]}
                >
                  <Input />
                </Form.Item>
              </Col>

              {/* Bank */}
              <Col span={8}>
                <Form.Item name="accountName" label="Account Name">
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item name="accountBsb" label="Account BSB">
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item name="accountNumber" label="Account Number">
                  <Input />
                </Form.Item>
              </Col>

              <Col span={8}>
                <Form.Item name="abn" label="ABN">
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item name="companyName" label="Company Name">
                  <Input />
                </Form.Item>
              </Col>
              <Col span={8}>
                <Form.Item
                  name="referredUserId"
                  label="Referred User"
                  rules={[{ required: true, message: 'Please Select Referred User' }]}
                >
                  <Select options={userOptions} />
                </Form.Item>
              </Col>

              {!!initialData && (
                <Col span={8}>
                  <Form.Item
                    name={['user', 'isActive']}
                    label="Status"
                    rules={[{ required: true }]}
                  >
                    <Radio.Group
                      options={[
                        { label: 'Active', value: true },
                        { label: 'Inactive', value: false },
                      ]}
                    />
                  </Form.Item>
                </Col>
              )}
            </Row>

            <div className="mt-3">
              <div className="flex items-center gap-2 mb-2">
                <Form.Item
                  name={['user', 'createLogin']}
                  valuePropName="checked"
                  initialValue={!!initialData ? initialData?.user?.createLogin : false}
                >
                  <Switch />
                </Form.Item>

                <Text className="font-medium">Create Login Details</Text>
              </div>

              {createLogin && (
                <>
                  <Row gutter={16}>
                    <Col span={8}>
                      <Form.Item
                        name={['user', 'loginId']}
                        label="Login ID"
                        rules={[{ required: true }]}
                      >
                        <Input disabled={hasLogin} />
                      </Form.Item>
                    </Col>
                  </Row>

                  {!hasLogin && (
                    <>
                      <div className="flex items-center gap-2 mb-2">
                        <Form.Item
                          name={['user', 'passwordAutoGenerated']}
                          valuePropName="checked"
                          initialValue={false}
                        >
                          <Switch />
                        </Form.Item>
                        <Text>Automatically generate a password and send email</Text>
                      </div>

                      {!passwordAutoGenerated && (
                        <>
                          <Row gutter={16}>
                            <Col span={8}>
                              <Form.Item
                                name={['user', 'manualPassword']}
                                label="Password"
                                rules={[{ required: true }]}
                              >
                                <Input.Password />
                              </Form.Item>
                            </Col>
                          </Row>

                          <div className="text-xs text-gray-500 ml-1 mb-2">
                            <p>Your password must have:</p>
                            <p>• 8+ characters</p>
                            <p>• Upper & lower letters</p>
                            <p>• Number</p>
                            <p>• Special character [!@#$%^&*-]</p>
                          </div>

                          <div className="flex items-center gap-2 mb-2">
                            <Form.Item
                              name={['user', 'nextLoginPasswordChange']}
                              valuePropName="checked"
                              initialValue={false}
                            >
                              <Switch />
                            </Form.Item>

                            <Text>Ask for partner change at next login</Text>
                          </div>

                          <div className="flex items-center gap-2 mb-2">
                            <Form.Item
                              name={['user', 'emailLoginCredentials']}
                              valuePropName="checked"
                              initialValue={false}
                            >
                              <Switch />
                            </Form.Item>
                            <Text>Email the Password</Text>
                          </div>
                        </>
                      )}
                    </>
                  )}
                </>
              )}
            </div>
          </Form>
        </div>
      </Modal>
    </>
  );
};

export default PartnerDetailModal;
