// Types for contractors
import { Status } from '@lib/constants/enum';

export type IUser = {
  usersId: string;
  name: string;
  email: string;
  loginId: string | null;
  roleId: string;
  roleName: string;
  phone: string | null;
  secondaryPhone: string | null;
  initials: string | null;
  reportingTo: string | null;
  reportingToName: string | null;
  designation: string | null;
  dateOfJoining: string | null;
  dateOfBirth: string | null;
  remark: string | null;
  consultantBio: string | null;
  photo: string | null;
  signature: string | null;
  isActive: boolean;
  isLocked: boolean;
  isVerified: boolean;
  rootUser: boolean;
  failedAttempts: number;
  nextLoginPasswordChange: boolean;
  passwordOption: boolean;
  emailLoginCredentials: boolean;
  addressId: string | null;
  useCompanyAddress: boolean;
  hasLogin: boolean;
  address: {
    city: string | null;
    stateId: string | null;
    zipCode: string | null;
    addressId: string | null;
    countryId: string | null;
    stateName: string | null;
    countryName: string | null;
    addressLine1: string | null;
    addressLine2: string | null;
  };
  createdAt: string;
  updatedAt: string;
};

export type invitedUser = {
  inviteId?: string;
  builderId?: string;
  email: string;
  role: string;
  invitedAt?: string;
};

export type ResetUserPassword = {
  passwordAutoGenerated: boolean;
  manualPassword?: boolean;
  nextLoginPasswordChange?: boolean;
  emailLoginCredentials?: boolean;
};


interface Pagination {
  totalItems: number;
  totalPages: number;
  currentPage: number;
  limit: number;
}

export interface invitedUserResponse {
  users: invitedUser[];
  pagination: Pagination;
}

export type UserInitialState = {
  users: IUser[];
  invitedUsers: invitedUser[];
  status: {
    users: {
      fetch: Status;
      create: Status;
    };
    invitedUsers: Status;
  };
};
