import { exportToExcel } from '@lib/utils/exportToExcel';

export const CustomerStatusReport = () => {
    const data = [
        {
            JobRefNo: 'MYH00001',
            CustomerName: 'Adam',
            Phone: '040612323',
            Email: 'ms@insimplify.com.au',
            JobAddress: 'Lot 300, Tarniet, VIC, 3029',
            AssigneeName: 'Murthy Muthuswamy',
            LeadSource: 'Internal',
            BuilderName: 'My Home',
            LandTitleDate: '',
            DepositAmount: '5,000.00',
            ClosedWonDate: '19-05-2020',
            ColorCost: '3,600.00',
            ColorStatus: 'Modify',
            ColorAppointmentDate: '',
            DraftingRequested: '',
            DraftingCompleted: '',
            DrawingFinalised: '',
            ConstructionStatus: 'Under Construction',
            ConstructionStage: 'Lockup Stage',
            PermitApprovedDate: '21-05-2020',
            ConstructionStartDate: '22-05-2020',
            Notes:
                'Murthy Muthuswamy on 19-10-2020:\nApplied for soil test\n\n' +
                'Murthy Muthuswamy on 19-07-2020:\nBase stage is completed\n\n' +
                'Adam on 09-09-2020:\nwhen is next stage',
            TotalCost: '341,000.00',
        },
        {
            JobRefNo: 'MYH00002',
            CustomerName: 'Scott',
            Phone: '2432324',
            Email: 'scott@insimploify.com.au',
            JobAddress: 'Lot 555, Melton, VIC, 3333',
            AssigneeName: 'Murthy Muthuswamy',
            LeadSource: 'Internal',
            BuilderName: 'My Home',
            LandTitleDate: '',
            DepositAmount: '3,500.00',
            ClosedWonDate: '20-05-2020',
            ColorCost: '5,000.00',
            ColorStatus: 'Approved - External',
            ColorAppointmentDate: '',
            DraftingRequested: '',
            DraftingCompleted: '',
            DrawingFinalised: '',
            ConstructionStatus: 'Under Construction',
            ConstructionStage: 'Preconstruction',
            PermitApprovedDate: '20-05-2020',
            ConstructionStartDate: '21-05-2020',
            Notes: '',
            TotalCost: '355,000.00',
        },
        {
            JobRefNo: 'MYH00003',
            CustomerName: 'Ben',
            Phone: '2343243424',
            Email: 'ben@insimplify.com.au',
            JobAddress: 'Lot 200, Melton, VIC, 3030',
            AssigneeName: 'Murthy Muthuswamy',
            LeadSource: 'Referral Partner',
            BuilderName: 'My Home',
            LandTitleDate: '',
            DepositAmount: '5,000.00',
            ClosedWonDate: '21-05-2020',
            ColorCost: '2,400.00',
            ColorStatus: 'Modify',
            ColorAppointmentDate: '',
            DraftingRequested: '',
            DraftingCompleted: '',
            DrawingFinalised: '',
            ConstructionStatus: 'Ready for Construction',
            ConstructionStage: 'Preconstruction',
            PermitApprovedDate: '',
            ConstructionStartDate: '',
            Notes: '',
            TotalCost: '513,900.00',
        },
        {
            JobRefNo: 'MYH00004',
            CustomerName: 'Yash',
            Phone: '0401232445',
            Email: 'yash@yashhomes.com.au',
            JobAddress: 'Lot 202, Melton, VIC, 2345',
            AssigneeName: 'Murthy Muthuswamy',
            LeadSource: 'Internal',
            BuilderName: 'My Home',
            LandTitleDate: '',
            DepositAmount: '2,000.00',
            ClosedWonDate: '28-05-2020',
            ColorCost: '800.00',
            ColorStatus: 'Approved',
            ColorAppointmentDate: '',
            DraftingRequested: '',
            DraftingCompleted: '',
            DrawingFinalised: '',
            ConstructionStatus: 'Under Construction',
            ConstructionStage: 'Base Stage',
            PermitApprovedDate: '03-08-2020',
            ConstructionStartDate: '04-08-2020',
            Notes: '',
            TotalCost: '250,800.00',
        },
        {
            JobRefNo: 'MYH00005',
            CustomerName: 'Lalitha',
            Phone: '0405063434',
            Email: 'lalitha@gmail.com',
            JobAddress: 'lot 500, Wyndhamvale, VIC, 3455',
            AssigneeName: 'Murthy Muthuswamy',
            LeadSource: '',
            BuilderName: 'My Home',
            LandTitleDate: '',
            DepositAmount: '5,000.00',
            ClosedWonDate: '03-06-2020',
            ColorCost: '400.00',
            ColorStatus: 'Approved',
            ColorAppointmentDate: '',
            DraftingRequested: '',
            DraftingCompleted: '',
            DrawingFinalised: '',
            ConstructionStatus: 'Under Construction',
            ConstructionStage: 'Preconstruction',
            PermitApprovedDate: '03-12-2020',
            ConstructionStartDate: '04-12-2020',
            Notes: '',
            TotalCost: '456,900.00',
        },
        {
            JobRefNo: 'MYH00007',
            CustomerName: 'Rakesh',
            Phone: '04534545',
            Email: 'rakesh@dreamhomez.com.au',
            JobAddress: 'Lot 300, Sydeny, VIC, 30303',
            AssigneeName: 'Murthy Muthuswamy',
            LeadSource: 'Referral Partner',
            BuilderName: 'My Home',
            LandTitleDate: '',
            DepositAmount: '5,000.00',
            ClosedWonDate: '11-06-2020',
            ColorCost: '250.00',
            ColorStatus: 'Approved',
            ColorAppointmentDate: '',
            DraftingRequested: '',
            DraftingCompleted: '',
            DrawingFinalised: '',
            ConstructionStatus: 'Under Construction',
            ConstructionStage: 'Base Stage',
            PermitApprovedDate: '11-06-2020',
            ConstructionStartDate: '12-06-2020',
            Notes: '',
            TotalCost: '465,560.00',
        },
    ];

    const column = {
        JobRefNo: { label: 'Job RefNo', color: 'FF0023BD' },
        CustomerName: { label: 'Customer Name', color: 'FF0023BD' },
        Phone: { label: 'Phone', color: 'FF0023BD' },
        Email: { label: 'Email', color: 'FF0023BD' },
        JobAddress: { label: 'Job Address', color: 'FF0023BD' },
        AssigneeName: { label: 'Assignee Name', color: 'FF0023BD' },
        LeadSource: { label: 'Lead Source', color: 'FF0023BD' },
        BuilderName: { label: 'Builder Name', color: 'FF0023BD' },
        LandTitleDate: { label: 'Land Title Date', color: 'FF0023BD' },
        DepositAmount: { label: 'Deposit Amount ($)', color: 'FF0023BD' },
        ClosedWonDate: { label: 'Closed Won Date', color: 'FF0023BD' },
        ColorCost: { label: 'Color Cost ($)', color: 'FF0023BD' },
        ColorStatus: { label: 'Color Status', color: 'FF0023BD' },
        ColorAppointmentDate: { label: 'Color Appointment Date', color: 'FF0023BD' },
        DraftingRequested: { label: 'Drafting Requested', color: 'FF0023BD' },
        DraftingCompleted: { label: 'Drafting Completed', color: 'FF0023BD' },
        DrawingFinalised: { label: 'Drawing Finalised', color: 'FF0023BD' },
        ConstructionStatus: { label: 'Construction Status', color: 'FF0023BD' },
        ConstructionStage: { label: 'Construction Stage', color: 'FF0023BD' },
        PermitApprovedDate: { label: 'Permit Approved Date', color: 'FF0023BD' },
        ConstructionStartDate: { label: 'Construction Start Date', color: 'FF0023BD' },
        Notes: { label: 'Notes', color: 'FF0023BD' },
        TotalCost: { label: 'Total Cost ($)', color: 'FF0023BD' },
    };

    exportToExcel({
        data: data,
        fileName: 'My Home_CustomerReport',
        sheetName: 'My Home_CustomerReport',
        columnHeaders: column,
    });
};
