import { exportToExcel } from '@lib/utils/exportToExcel';

export const InvoicePaymentsReport = () => {
    const data = [
        {
            InvoiceID: "MYH00001-I1",
            Name: "Adam",
            JobAddress: "Lot 300, Tarniet, VIC, 3029",
            InvoiceDescription: "Initial Deposit _+ sOIL TEST",
            InvoiceStatus: "Overdue",
            InvoiceAmount: "6,000.00",
            CreatedUser: "Murthy Muthuswamy",
            InvoiceDate: "19-05-2020",
            DueDate: "29-05-2020",
            ReceiptID: "",
            PaidAmount: "",
            PaymentDate: "",
            ModeOfPayment: "",
            Assignee: "Murthy Muthuswamy",
            PaymentRemark: "",
        },
        {
            InvoiceID: "MYH00002-I1",
            Name: "Scott",
            JobAddress: "Lot 555, Melton, VIC, 3333",
            InvoiceDescription: "Initial Deposit",
            InvoiceStatus: "Paid",
            InvoiceAmount: "3,500.00",
            CreatedUser: "Murthy Muthuswamy",
            InvoiceDate: "20-05-2020",
            DueDate: "20-05-2020",
            ReceiptID: "MYH00002-R1",
            PaidAmount: "3,500.00",
            PaymentDate: "20-05-2020",
            ModeOfPayment: "",
            Assignee: "Murthy Muthuswamy",
            PaymentRemark: "",
        },
        {
            InvoiceID: "MYH00003-I1",
            Name: "Ben",
            JobAddress: "Lot 200, Melton, VIC, 3030",
            InvoiceDescription: "Initial Deposit",
            InvoiceStatus: "Paid",
            InvoiceAmount: "5,000.00",
            CreatedUser: "Murthy Muthuswamy",
            InvoiceDate: "21-05-2020",
            DueDate: "21-05-2020",
            ReceiptID: "MYH00003-R1",
            PaidAmount: "5,000.00",
            PaymentDate: "21-05-2020",
            ModeOfPayment: "",
            Assignee: "Murthy Muthuswamy",
            PaymentRemark: "",
        },
        {
            InvoiceID: "MYH00004-I1",
            Name: "Yash",
            JobAddress: "Lot 202, Melton, VIC, 2345",
            InvoiceDescription: "Initial Deposit",
            InvoiceStatus: "Paid",
            InvoiceAmount: "2,000.00",
            CreatedUser: "Murthy Muthuswamy",
            InvoiceDate: "28-05-2020",
            DueDate: "28-05-2020",
            ReceiptID: "MYH00004-R1",
            PaidAmount: "2,000.00",
            PaymentDate: "28-05-2020",
            ModeOfPayment: "",
            Assignee: "Murthy Muthuswamy",
            PaymentRemark: "",
        },
        {
            InvoiceID: "MYH00005-I1",
            Name: "Lalitha",
            JobAddress: "lot 500, Wyndhamvale, VIC, 3455",
            InvoiceDescription: "Initial Deposit",
            InvoiceStatus: "Paid",
            InvoiceAmount: "5,000.00",
            CreatedUser: "Murthy Muthuswamy",
            InvoiceDate: "03-06-2020",
            DueDate: "03-06-2020",
            ReceiptID: "MYH00005-R1",
            PaidAmount: "5,000.00",
            PaymentDate: "03-06-2020",
            ModeOfPayment: "",
            Assignee: "Murthy Muthuswamy",
            PaymentRemark: "",
        },
    ];


    const column = {
        InvoiceID: { label: 'Invoice ID', color: 'FF0023BD' },
        Name: { label: 'Name', color: 'FF0023BD' },
        JobAddress: { label: 'Job Address', color: 'FF0023BD' },
        InvoiceDescription: { label: 'Invoice Description', color: 'FF0023BD' },
        InvoiceStatus: { label: 'Invoice Status', color: 'FF0023BD' },
        InvoiceAmount: { label: 'Invoice Amount', color: 'FF0023BD' },
        CreatedUser: { label: 'Created User', color: 'FF0023BD' },
        InvoiceDate: { label: 'Invoice Date', color: 'FF0023BD' },
        DueDate: { label: 'Due Date', color: 'FF0023BD' },
        ReceiptID: { label: 'Receipt ID', color: 'FF0023BD' },
        PaidAmount: { label: 'Paid Amount', color: 'FF0023BD' },
        PaymentDate: { label: 'Payment Date', color: 'FF0023BD' },
        ModeOfPayment: { label: 'Mode of Payment', color: 'FF0023BD' },
        Assignee: { label: 'Assignee', color: 'FF0023BD' },
        PaymentRemark: { label: 'PaymentRemark', color: 'FF0023BD' },
    };

    exportToExcel({
        data: data,
        fileName: 'My Home_InvoicePaymentReport',
        sheetName: 'My Home_InvoicePaymentReport',
        columnHeaders: column,
        title: "InvoicePayment Report"
    });
};
