import { exportToExcel } from '@lib/utils/exportToExcel';

export const LandTitleForcastReport = () => {
    const data = [
        {
            ReferenceID: 'MYH00665',
            CustomerName: 'Joshua Ewing',
            JobAddress: '91 Hague L In numquam proident, Ex qui quia aut aute, VIC, 2075',
            BuilderName: 'My Home',
            DwellingType: 'Single Storey',
            TitleStatus: 'Titled',
            LandTitleDate: '01/Oct/2025',
            SiteStartDate: '30/Dec/2025',
            EstateName: 'Yoshi Witt',
            Consultant: 'Kishan',
            ConsStageName: '',
            WorkflowStageName: 'Deposit',
        },
        {
            ReferenceID: 'MYH00077',
            CustomerName: 'SK',
            JobAddress: '232131, 123213, VIC, 123123',
            BuilderName: 'My Home',
            DwellingType: 'Single Storey',
            TitleStatus: 'Titled',
            LandTitleDate: '29/Sep/2020',
            SiteStartDate: '28/Dec/2020',
            EstateName: '',
            Consultant: 'Murthy Muthuswamy',
            ConsStageName: '',
            WorkflowStageName: '',
        },
        {
            ReferenceID: 'MYH00072',
            CustomerName: 'Ecoliv',
            JobAddress: 'Lot 4567, Tarneit, VIC, 3333',
            BuilderName: 'My Home',
            DwellingType: 'Single Storey',
            TitleStatus: 'Titled',
            LandTitleDate: '30/Sep/2020',
            SiteStartDate: '29/Dec/2020',
            EstateName: '',
            Consultant: 'Murthy Muthuswamy',
            ConsStageName: '',
            WorkflowStageName: '',
        },
        {
            ReferenceID: 'MYH00524',
            CustomerName: 'bhilinder bawa',
            JobAddress: 'Lot 123, ghghh nbjjjnjnj, dddddd990, QLD, 7777',
            BuilderName: 'My Home',
            DwellingType: 'Single Storey',
            TitleStatus: 'Titled',
            LandTitleDate: '16/Dec/2023',
            SiteStartDate: '15/Mar/2024',
            EstateName: '',
            Consultant: 'Bawa',
            ConsStageName: '',
            WorkflowStageName: 'Deposit',
        },
        {
            ReferenceID: 'MYH00610',
            CustomerName: 'Jodie',
            JobAddress: 'Building 22/330 Swanston St, Melbourne, VIC, 3000',
            BuilderName: 'My Home',
            DwellingType: 'Single Storey',
            TitleStatus: 'Estimated',
            LandTitleDate: '11/Dec/2024',
            SiteStartDate: '11/Mar/2025',
            EstateName: '',
            Consultant: 'Murthy Muthuswamy',
            ConsStageName: '',
            WorkflowStageName: 'Deposit',
        },
        {
            ReferenceID: 'MYH00611',
            CustomerName: 'Kamron Jones',
            JobAddress: '13 Shropshire St, Queanbeyan, VIC, 2620',
            BuilderName: 'My Home',
            DwellingType: 'Single Storey',
            TitleStatus: 'Confirmed',
            LandTitleDate: '11/Dec/2024',
            SiteStartDate: '11/Mar/2025',
            EstateName: '',
            Consultant: 'Murthy Muthuswamy',
            ConsStageName: '',
            WorkflowStageName: 'Deposit',
        },
    ];

    const column = {
        ReferenceID: { label: 'Reference ID', color: 'FF0023BD' },
        CustomerName: { label: 'Customer Name', color: 'FF0023BD' },
        JobAddress: { label: 'Job Address', color: 'FF0023BD' },
        BuilderName: { label: 'Builder Name', color: 'FF0023BD' },
        DwellingType: { label: 'Dwelling Type', color: 'FF0023BD' },
        TitleStatus: { label: 'Title Status', color: 'FF0023BD' },
        LandTitleDate: { label: 'Land TitleDate', color: 'FF0023BD' },
        SiteStartDate: { label: 'Site StartDate', color: 'FF0023BD' },
        EstateName: { label: 'Estate Name', color: 'FF0023BD' },
        Consultant: { label: 'Consultant', color: 'FF0023BD' },
        ConsStageName: { label: 'ConsStageName', color: 'FF0023BD' },
        WorkflowStageName: { label: 'WorkflowStageName', color: 'FF0023BD' },
    };

    exportToExcel({
        data: data,
        fileName: 'My Home_LandTitleForecastReport',
        sheetName: 'My Home_LandTitleForecastReport',
        columnHeaders: column,
    });
};
