import { exportToExcel } from '@lib/utils/exportToExcel';

export const VariationReport = () => {
    const data = [
        {
            VariationID: 'MYH00663-V1',
            Name: 'Mathew',
            JobAddress: 'Lot 34 Chelsea Street, Tarneit, VIC, 3029',
            Description: 'ixed Site costs including var',
            Status: 'Approved',
            VariationSent: '',
            VariationSigned: '',
            InvoiceCreated: 'No',
            InvoiceSent: 'No',
            Amount: '12,000.00',
            Payment: '',
            ExtensionSent: 'Never',
            CreatedDate: '30-09-2025',
            CreatedUser: 'Murthy Muthuswamy',
        },
        {
            VariationID: 'MYH00653-V2',
            Name: 'Balram Test',
            JobAddress: '123, epping street, Melbourne, VIC, 1245',
            Description: 'abinets',
            Status: 'Sent to customer',
            VariationSent: '24-09-2025',
            VariationSigned: '',
            InvoiceCreated: 'No',
            InvoiceSent: 'No',
            Amount: '1,800.00',
            Payment: '',
            ExtensionSent: 'Never',
            CreatedDate: '24-09-2025',
            CreatedUser: 'Harry',
        },
        {
            VariationID: 'MYH00637-V1',
            Name: 'John Wick',
            JobAddress: 'Suite 10, 45 Tallis Circuit, Truganina, VIC, 3029',
            Description: 'xtra vanity',
            Status: 'Variation Unsent',
            VariationSent: '',
            VariationSigned: '',
            InvoiceCreated: 'No',
            InvoiceSent: 'No',
            Amount: '6,000.00',
            Payment: '',
            ExtensionSent: 'Never',
            CreatedDate: '24-09-2025',
            CreatedUser: 'Murthy Muthuswamy',
        },
        {
            VariationID: 'MYH00660-V1',
            Name: 'Mathew',
            JobAddress: 'Lot 333 ABC Street, Cobblebank, VIC, 3338',
            Description: 'ixed Site costs including var',
            Status: 'Approved',
            VariationSent: '',
            VariationSigned: '',
            InvoiceCreated: 'No',
            InvoiceSent: 'No',
            Amount: '12,000.00',
            Payment: '',
            ExtensionSent: 'Never',
            CreatedDate: '22-09-2025',
            CreatedUser: 'Murthy Muthuswamy',
        },
        {
            VariationID: 'MYH00657-V1',
            Name: 'Mat',
            JobAddress: 'Lot 67 Melbourne Rd, Epping, VIC, 3030',
            Description: 'an Points-No Installation',
            Status: 'Draft',
            VariationSent: '',
            VariationSigned: '',
            InvoiceCreated: 'No',
            InvoiceSent: 'No',
            Amount: '330',
            Payment: '',
            ExtensionSent: 'Never',
            CreatedDate: '11-09-2025',
            CreatedUser: 'Murthy Muthuswamy',
        },
        {
            VariationID: 'MYH00659-V1',
            Name: 'Brad',
            JobAddress: 'Lot 223 Sayers Road, Tarneit, VIC, 3029',
            Description: 'ixed Site costs including var',
            Status: 'Draft',
            VariationSent: '',
            VariationSigned: '',
            InvoiceCreated: 'No',
            InvoiceSent: 'No',
            Amount: '12,000.00',
            Payment: '',
            ExtensionSent: 'Never',
            CreatedDate: '09-09-2025',
            CreatedUser: 'Murthy Muthuswamy',
        },
    ];

    const column = {
        VariationID: { label: 'Variation ID', color: 'FF0023BD' },
        Name: { label: 'Name', color: 'FF0023BD' },
        JobAddress: { label: 'Job Address', color: 'FF0023BD' },
        Description: { label: 'Description', color: 'FF0023BD' },
        Status: { label: 'Status', color: 'FF0023BD' },
        VariationSent: { label: 'Variation Sent', color: 'FF0023BD' },
        VariationSigned: { label: 'Variation Signed', color: 'FF0023BD' },
        InvoiceCreated: { label: 'Invoice Created', color: 'FF0023BD' },
        InvoiceSent: { label: 'Invoice Sent', color: 'FF0023BD' },
        Amount: { label: 'Amount', color: 'FF0023BD' },
        Payment: { label: 'Payment', color: 'FF0023BD' },
        ExtensionSent: { label: 'Extension Sent', color: 'FF0023BD' },
        CreatedDate: { label: 'Created Date', color: 'FF0023BD' },
        CreatedUser: { label: 'Created User', color: 'FF0023BD' },
    };

    exportToExcel({
        data: data,
        fileName: 'My Home_VariationReport',
        sheetName: 'My Home_VariationReport',
        columnHeaders: column,
        title: 'Variation Report',
    });
};
